"""Enums for the notifications application."""

from enum import Enum


class NotificationType(str, Enum):
    OUTBID = "OUTBID"
    AUCTION_WON = "AUCTION_WON"
    BID_PLACED = "BID_PLACED"
    ITEM_SHIPPED = "ITEM_SHIPPED"
    ESCROW_RELEASED = "ESCROW_RELEASED"
    DISPUTE_OPENED = "DISPUTE_OPENED"
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    AUCTION_ENDED = "AUCTION_ENDED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_SHIPPED = "ORDER_SHIPPED"
    ORDER_DELIVERED = "ORDER_DELIVERED"
    WALLET_CREDITED = "WALLET_CREDITED"
    WALLET_DEBITED = "WALLET_DEBITED"
    ACCOUNT_VERIFIED = "ACCOUNT_VERIFIED"


class NotificationReferenceType(str, Enum):
    BID = "BID"
    AUCTION = "AUCTION"
    ORDER = "ORDER"
    DISPUTE = "DISPUTE"
    ESCROW = "ESCROW"
    WALLET_TRANSACTION = "WALLET_TRANSACTION"
