"""Database connection and session configuration.

This module sets up the async SQLAlchemy engine, session factory,
and declarative base classes used across all application models.
"""

import asyncio
import logging
import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from config.settings import settings

logger = logging.getLogger(__name__)

# Async engine configured with a connection pool suitable for production use.
# pool_size controls persistent connections; max_overflow allows temporary bursts.
engine = create_async_engine(
    settings.database_url,
    future=True,
    pool_size=settings.database_pool_size,
    max_overflow=settings.database_max_overflow,
    pool_timeout=settings.database_pool_timeout,
    pool_recycle=settings.database_pool_recycle,
    pool_pre_ping=True,  # tests connection before use
    echo=False,
)

# Session factory bound to the async engine.
# expire_on_commit=False keeps model attributes accessible after a commit
# without requiring an additional database round-trip.
AsyncSessionLocal = async_sessionmaker(
    engine, class_=AsyncSession, expire_on_commit=False
)


# check DB connection
async def check_database_connection() -> bool:
    """Tests database reachability with a simple SELECT 1.

    Returns:
        bool: True if reachable, False if not.
    """
    try:
        async with engine.connect() as conn:
            await conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


async def wait_for_database(retries: int = 3, delay: int = 5) -> None:
    """Block startup until the database is reachable.

    Retries up to `retries` times with `delay` seconds between attempts.
    Raises RuntimeError if all attempts fail — prevents app from starting
    in a broken state.

    Args:
        retries: Number of attempts before giving up.
        delay: Seconds to wait between attempts.
    """
    for attempt in range(1, retries + 1):
        if await check_database_connection():
            logger.info("Database connection verified (attempt %d)", attempt)
            return

        logger.warning(
            "Database not ready, retrying in %ds (attempt %d/%d)",
            delay,
            attempt,
            retries,
        )
        await asyncio.sleep(delay)

    logger.critical(
        "Database unreachable after %d attempts - aborting startup", retries
    )
    raise RuntimeError("Cannot connect to database. Aborting.")


class Base(DeclarativeBase):
    """SQLAlchemy declarative base.

    All ORM models in the application must inherit from this class.
    It provides the metadata registry used by Alembic for autogenerate
    migration support.
    """

    pass


class BaseModel(Base):
    """Abstract base model with shared audit fields.

    Provides common columns that every concrete model inherits automatically:

    Attributes:
        id: UUID primary key generated by Python (not the database),
            ensuring uniqueness before the row is persisted.
        created_at: Timezone-aware timestamp set by the database on INSERT.
        updated_at: Timezone-aware timestamp refreshed by the database on
            every UPDATE.

    Note:
        This class is abstract (``__abstract__ = True``) and does not
        produce its own database table.

    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
