"""Database connection and session configuration.

This module sets up the async SQLAlchemy engine, session factory,
and declarative base classes used across all application models.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from config.settings import settings

# Async engine configured with a connection pool suitable for production use.
# pool_size controls persistent connections; max_overflow allows temporary bursts.
engine = create_async_engine(
    settings.database_url, future=True, pool_size=10, max_overflow=20, echo=False
)

# Session factory bound to the async engine.
# expire_on_commit=False keeps model attributes accessible after a commit
# without requiring an additional database round-trip.
AsyncSessionLocal = async_sessionmaker(
    engine, class_=AsyncSession, expire_on_commit=False
)


class Base(DeclarativeBase):
    """SQLAlchemy declarative base.

    All ORM models in the application must inherit from this class.
    It provides the metadata registry used by Alembic for autogenerate
    migration support.
    """

    pass


class BaseModel(Base):
    """Abstract base model with shared audit fields.

    Provides common columns that every concrete model inherits automatically:

    Attributes:
        id: UUID primary key generated by Python (not the database),
            ensuring uniqueness before the row is persisted.
        created_at: Timezone-aware timestamp set by the database on INSERT.
        updated_at: Timezone-aware timestamp refreshed by the database on
            every UPDATE.

    Note:
        This class is abstract (``__abstract__ = True``) and does not
        produce its own database table.

    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
