"""ORM models for payment tracking."""

import uuid
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from config.database import BaseModel

if TYPE_CHECKING:
    from apps.wallet.models import Wallet


class Payment(BaseModel):
    """External payment tracking for wallet funding.

    Tracks the full lifecycle of payments through external providers
    like Flutterwave. This is the payment gateway abstraction layer.

    Attributes:
        transaction_reference: Our unique reference (APF-xxx format).
        provider_reference: Provider's reference (e.g., Flutterwave's flw_ref).
        wallet_id: Foreign key to the wallet being funded.
        amount: Payment amount, precision 10/2.
        currency: ISO 4217 currency code.
        provider: Payment provider (flutterwave, bank_transfer, etc.).
        status: Current payment status (pending, completed, failed).
        provider_response: Full JSON response from provider for audit.
        webhook_received_at: Timestamp when webhook was received.
        verified_at: Timestamp when payment was verified with provider.
        wallet_transaction_id: Link to WalletTransaction created after completion.
    """

    __tablename__ = "payments"
    __table_args__ = (
        CheckConstraint("amount > 0", name="ck_payment_amount"),
        Index("ix_payments_transaction_reference", "transaction_reference"),
        Index("ix_payments_wallet_id", "wallet_id"),
        Index("ix_payments_status", "status"),
    )

    # Our reference (generated by us)
    transaction_reference: Mapped[str] = mapped_column(
        String(100), unique=True, nullable=False
    )

    # Provider details
    provider: Mapped[str] = mapped_column(
        String(50), nullable=False, default="FLUTTERWAVE"
    )
    provider_reference: Mapped[str] = mapped_column(String(100), nullable=True)

    # Payment details
    wallet_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("wallets.id"), nullable=False
    )
    amount: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="NGN")

    # Status tracking
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="PENDING")

    # Optimistic locking
    version: Mapped[int] = mapped_column(default=1, nullable=False)

    # Audit trail
    provider_response: Mapped[str] = mapped_column(
        Text, nullable=True
    )  # Store as JSON string
    webhook_received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    verified_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Payment Tracking
    payment_link: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    payment_link_expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Link to wallet transaction (created after payment completes)
    wallet_transaction_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    # Relationships
    wallet: Mapped["Wallet"] = relationship("Wallet", back_populates="payments")
