"""add

Revision ID: 0c8cac941173
Revises: d7ea1591e04b
Create Date: 2026-03-22 10:11:19.319184

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c8cac941173"
down_revision: Union[str, Sequence[str], None] = "d7ea1591e04b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_email_verification_tokens_user_id"),
        "email_verification_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_auction_highest_bud_id",
        "auctions",
        "bids",
        ["highest_bid_id"],
        ["id"],
        use_alter=True,
    )
    op.drop_constraint(op.f("orders_escrow_id_key"), "orders", type_="unique")
    op.create_foreign_key(
        "fk_order_dispute_id",
        "orders",
        "disputes",
        ["dispute_id"],
        ["id"],
        use_alter=True,
    )
    op.drop_column("orders", "escrow_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("escrow_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint("fk_order_dispute_id", "orders", type_="foreignkey")
    op.create_unique_constraint(
        op.f("orders_escrow_id_key"),
        "orders",
        ["escrow_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("fk_auction_highest_bud_id", "auctions", type_="foreignkey")
    op.drop_index(
        op.f("ix_email_verification_tokens_user_id"),
        table_name="email_verification_tokens",
    )
    op.drop_table("email_verification_tokens")
    # ### end Alembic commands ###
