"""Add kyc models and user tier.

Revision ID: 0e7589e1c450
Revises: 15dffe28db1b
Create Date: 2026-04-08 07:23:13.222690

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e7589e1c450"
down_revision: Union[str, Sequence[str], None] = "15dffe28db1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kyc_document",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "NATIONAL_ID",
                "DRIVERS_LICENSE",
                "PASSPORT",
                "BANK_STATEMENT",
                "UTILITY_BILL",
                "SELFIE",
                name="kycdocuments",
            ),
            nullable=False,
        ),
        sa.Column("document_url", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "VERIFIED", "REJECTED", "EXPIRED", name="kycstatus"),
            nullable=False,
        ),
        sa.Column("verified_by_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kyc_document_user_id"), "kyc_document", ["user_id"], unique=False
    )
    op.create_table(
        "kyc_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "current_tier",
            sa.Enum("TIER_1", "TIER_2", "TIER_3", name="kyctier"),
            nullable=False,
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("tier_1_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bvn_hash", sa.String(length=255), nullable=True),
        sa.Column("bvn_verified", sa.Boolean(), nullable=False),
        sa.Column("bvn_verification_reference", sa.String(), nullable=True),
        sa.Column("bvn_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tier_2_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("address_verified", sa.Boolean(), nullable=False),
        sa.Column("bank_statement_verified", sa.Boolean(), nullable=False),
        sa.Column("tier_3_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_address", sa.String(), nullable=True),
        sa.Column("id_number", sa.String(), nullable=True),
        sa.Column("bvn_attempt_count", sa.Integer(), nullable=False),
        sa.Column("bvn_attempt_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_verification_attempt", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kyc_profiles_user_id"), "kyc_profiles", ["user_id"], unique=True
    )
    op.add_column(
        "users",
        sa.Column(
            "kyc_tier",
            sa.Enum("TIER_1", "TIER_2", "TIER_3", name="kyctier"),
            nullable=False,
            server_default="TIER_1",
        ),
    )
    op.alter_column("users", "kyc_tier", server_default=None)
    op.create_index(op.f("ix_users_kyc_tier"), "users", ["kyc_tier"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_kyc_tier"), table_name="users")
    op.drop_column("users", "kyc_tier")
    op.drop_index(op.f("ix_kyc_profiles_user_id"), table_name="kyc_profiles")
    op.drop_table("kyc_profiles")
    op.drop_index(op.f("ix_kyc_document_user_id"), table_name="kyc_document")
    op.drop_table("kyc_document")
    # ### end Alembic commands ###
