"""Added bio field to Seller Profile table

Revision ID: 195a1220d3fa
Revises: 3a7f2e1d9c84
Create Date: 2026-06-09 01:52:08.129156

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "195a1220d3fa"
down_revision: Union[str, Sequence[str], None] = "3a7f2e1d9c84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seller_profiles", sa.Column("bio", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller_profiles", "bio")
    # ### end Alembic commands ###
