"""added_public_id_to_image

Revision ID: 44aea174975d
Revises: 5d0cccc84f17
Create Date: 2026-03-28 13:47:20.888752

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44aea174975d"
down_revision: Union[str, Sequence[str], None] = "5d0cccc84f17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_images", sa.Column("public_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item_images", "public_id")
    # ### end Alembic commands ###
