"""add_payment_link_fields_to_payments

Revision ID: 744b92bb280c
Revises: fb1bf731c593
Create Date: 2026-03-25 19:22:35.425808

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "744b92bb280c"
down_revision: Union[str, Sequence[str], None] = "fb1bf731c593"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("payment_link", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "payments",
        sa.Column("payment_link_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "payment_link_expires_at")
    op.drop_column("payments", "payment_link")
    # ### end Alembic commands ###
