"""Add tracking_number to orders.

Revision ID: 9bb54b826f56
Revises: 44aea174975d
Create Date: 2026-03-31 09:27:36.669375

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bb54b826f56"
down_revision: Union[str, Sequence[str], None] = "44aea174975d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "tracking_number")
    # ### end Alembic commands ###
