"""initial_database_schema

Revision ID: d7ea1591e04b
Revises:
Create Date: 2026-03-19 12:12:51.359986

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7ea1591e04b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "account_status",
            sa.Enum(
                "ACTIVE", "SUSPENDED", "BANNED", "DEACTIVATED", name="accountstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "USER", "STAFF", "SUPERUSER", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(
        op.f("ix_users_account_status"), "users", ["account_status"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "auctions",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("highest_bid_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "ENDED_WITH_WINNER",
                "ENDED_NO_BIDS",
                "SETTLED",
                "SCHEDULED",
                "CANCELLED",
                "SETTLEMENT_FAILED",
                name="auctionstatus",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reserve_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("bid_increment", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > starts_at", name="check_ends_after_starts"),
        sa.CheckConstraint(
            "reserve_price >= 0", name="check_reserve_price_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["highest_bid_id"],
            ["bids.id"],
            name="fk_auction_highest_bud_id",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auctions_ends_at"), "auctions", ["ends_at"], unique=False)
    op.create_index(
        op.f("ix_auctions_seller_id"), "auctions", ["seller_id"], unique=False
    )
    op.create_index(op.f("ix_auctions_status"), "auctions", ["status"], unique=False)
    op.create_index(
        "ix_auctions_status_ends_at", "auctions", ["status", "ends_at"], unique=False
    )
    op.create_table(
        "items",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "condition",
            sa.Enum("NEW", "LIKE_NEW", "GOOD", "FAIR", "POOR", name="itemcondition"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                "LISTED",
                "SOLD",
                "IN_AUCTION",
                "ARCHIVED",
                name="itemstatus",
            ),
            nullable=False,
        ),
        sa.Column("weight_kg", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("dimensions", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_items_category_id"), "items", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_items_seller_id"), "items", ["seller_id"], unique=False)
    op.create_index(op.f("ix_items_status"), "items", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "OUTBID",
                "AUCTION_WON",
                "BID_PLACED",
                "ITEM_SHIPPED",
                "ESCROW_RELEASED",
                "DISPUTE_OPENED",
                "DISPUTE_RESOLVED",
                "PAYMENT_RECEIVED",
                "AUCTION_ENDED",
                "ORDER_CREATED",
                "ORDER_SHIPPED",
                "ORDER_DELIVERED",
                "WALLET_CREDITED",
                "WALLET_DEBITED",
                "ACCOUNT_VERIFIED",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reference_id", sa.UUID(), nullable=True),
        sa.Column(
            "reference_type",
            sa.Enum(
                "BID",
                "AUCTION",
                "ORDER",
                "DISPUTE",
                "ESCROW",
                "WALLET_TRANSACTION",
                name="notificationreferencetype",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_index(
        "ix_notifications_user_unread",
        "notifications",
        ["user_id", "is_read"],
        unique=False,
        postgresql_where=sa.text("is_read = false"),
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "seller_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "seller_type",
            sa.Enum("CASUAL", "RETAIL", "WHOLESALE", name="sellertype"),
            nullable=False,
        ),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("bank_acct_number", sa.String(length=50), nullable=True),
        sa.Column("bank_name", sa.String(length=50), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column(
            "onboarding_intent",
            sa.Enum("BUY", "SELL", "BOTH", name="onboardingintent"),
            nullable=True,
        ),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("total_sales", sa.Integer(), nullable=True),
        sa.Column("total_purchases", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "wallets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("available_funds", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("locked_funds", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("escrow_funds", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("available_funds >= 0", name="ck_wallet_available_funds"),
        sa.CheckConstraint("escrow_funds >= 0", name="ck_wallet_escrow_funds"),
        sa.CheckConstraint("locked_funds >= 0", name="ck_wallet_locked_funds"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=True)
    op.create_table(
        "auction_items",
        sa.Column("auction_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("starting_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="check_quantity_positive"),
        sa.CheckConstraint(
            "starting_price >= 0", name="check_starting_price_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["auction_id"],
            ["auctions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auction_id", "item_id", name="uq_auction_item"),
    )
    op.create_index(
        op.f("ix_auction_items_auction_id"),
        "auction_items",
        ["auction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auction_items_item_id"), "auction_items", ["item_id"], unique=False
    )
    op.create_table(
        "item_images",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_item_images_item_id"), "item_images", ["item_id"], unique=False
    )
    op.create_table(
        "verification_docs",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("balance_before", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("transaction_type", sa.String(length=15), nullable=False),
        sa.Column("direction", sa.String(length=6), nullable=False),
        sa.Column("balance_type", sa.String(length=12), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=True),
        sa.Column("reference_type", sa.String(length=20), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_wallet_transaction_amount"),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_wallet_transactions_reference",
        "wallet_transactions",
        ["reference_id", "reference_type"],
        unique=False,
    )
    op.create_index(
        "ix_wallet_transactions_type",
        "wallet_transactions",
        ["transaction_type"],
        unique=False,
    )
    op.create_index(
        "ix_wallet_transactions_wallet_id",
        "wallet_transactions",
        ["wallet_id"],
        unique=False,
    )
    op.create_table(
        "bids",
        sa.Column("auction_id", sa.UUID(), nullable=False),
        sa.Column("bidder_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "OUTBID", "WON", "LOST", "RELEASED", name="bidstatus"),
            nullable=False,
        ),
        sa.Column("wallet_transaction_id", sa.UUID(), nullable=True),
        sa.Column(
            "placed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_bid_amount"),
        sa.ForeignKeyConstraint(
            ["auction_id"],
            ["auctions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bidder_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_transaction_id"],
            ["wallet_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bids_auction_amount", "bids", ["auction_id", "amount"], unique=False
    )
    op.create_index(op.f("ix_bids_auction_id"), "bids", ["auction_id"], unique=False)
    op.create_index(op.f("ix_bids_bidder_id"), "bids", ["bidder_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("auction_id", sa.UUID(), nullable=False),
        sa.Column("auction_item_id", sa.UUID(), nullable=False),
        sa.Column("buyer_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("dispute_id", sa.UUID(), nullable=True),
        sa.Column("escrow_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_SHIPMENT",
                "SHIPPED",
                "DELIVERED",
                "DISPUTED",
                "COMPLETED",
                "CANCELLED",
                "REFUNDED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("shipping_deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispute_raised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["auction_id"],
            ["auctions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["auction_item_id"],
            ["auction_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dispute_id"], ["disputes.id"], name="fk_order_dispute_id", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["escrow_id"], ["escrows.id"], name="fk_order_escrow_id", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dispute_id"),
        sa.UniqueConstraint("escrow_id"),
    )
    op.create_index(
        op.f("ix_orders_auction_id"), "orders", ["auction_id"], unique=False
    )
    op.create_index(op.f("ix_orders_buyer_id"), "orders", ["buyer_id"], unique=False)
    op.create_index(op.f("ix_orders_seller_id"), "orders", ["seller_id"], unique=False)
    op.create_index(
        "ix_orders_shipping_deadline",
        "orders",
        ["shipping_deadline_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING_SHIPMENT'"),
    )
    op.create_index(
        op.f("ix_orders_shipping_deadline_at"),
        "orders",
        ["shipping_deadline_at"],
        unique=False,
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "disputes",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("auction_id", sa.UUID(), nullable=False),
        sa.Column("raised_by_id", sa.UUID(), nullable=False),
        sa.Column("against_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "UNDER_REVIEW",
                "RESOLVED",
                "DISMISSED",
                "CLOSED",
                name="disputestatus",
            ),
            nullable=False,
        ),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_by_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["against_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["auction_id"],
            ["auctions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raised_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_disputes_order_id"), "disputes", ["order_id"], unique=False
    )
    op.create_table(
        "escrows",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("auction_id", sa.UUID(), nullable=False),
        sa.Column("winner_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "commission_amount", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "HOLDING",
                "RELEASED",
                "REFUNDED",
                "DISPUTED",
                "FAILED",
                name="escrowstatus",
            ),
            nullable=False,
        ),
        sa.Column("auto_release_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_escrow_amount"),
        sa.ForeignKeyConstraint(
            ["auction_id"],
            ["auctions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "dispute_evidence",
        sa.Column("dispute_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum("IMAGE", "VIDEO", "DOCUMENT", name="evidencefiletype"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dispute_id"],
            ["disputes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dispute_evidence_dispute_id"),
        "dispute_evidence",
        ["dispute_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dispute_evidence_dispute_id"), table_name="dispute_evidence")
    op.drop_table("dispute_evidence")
    op.drop_table("escrows")
    op.drop_index(op.f("ix_disputes_order_id"), table_name="disputes")
    op.drop_table("disputes")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_shipping_deadline_at"), table_name="orders")
    op.drop_index(
        "ix_orders_shipping_deadline",
        table_name="orders",
        postgresql_where=sa.text("status = 'PENDING_SHIPMENT'"),
    )
    op.drop_index(op.f("ix_orders_seller_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_buyer_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_auction_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_bids_bidder_id"), table_name="bids")
    op.drop_index(op.f("ix_bids_auction_id"), table_name="bids")
    op.drop_index("ix_bids_auction_amount", table_name="bids")
    op.drop_table("bids")
    op.drop_index("ix_wallet_transactions_wallet_id", table_name="wallet_transactions")
    op.drop_index("ix_wallet_transactions_type", table_name="wallet_transactions")
    op.drop_index("ix_wallet_transactions_reference", table_name="wallet_transactions")
    op.drop_table("wallet_transactions")
    op.drop_table("verification_docs")
    op.drop_index(op.f("ix_item_images_item_id"), table_name="item_images")
    op.drop_table("item_images")
    op.drop_index(op.f("ix_auction_items_item_id"), table_name="auction_items")
    op.drop_index(op.f("ix_auction_items_auction_id"), table_name="auction_items")
    op.drop_table("auction_items")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_table("seller_profiles")
    op.drop_index(
        op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(
        "ix_notifications_user_unread",
        table_name="notifications",
        postgresql_where=sa.text("is_read = false"),
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_items_status"), table_name="items")
    op.drop_index(op.f("ix_items_seller_id"), table_name="items")
    op.drop_index(op.f("ix_items_category_id"), table_name="items")
    op.drop_table("items")
    op.drop_index("ix_auctions_status_ends_at", table_name="auctions")
    op.drop_index(op.f("ix_auctions_status"), table_name="auctions")
    op.drop_index(op.f("ix_auctions_seller_id"), table_name="auctions")
    op.drop_index(op.f("ix_auctions_ends_at"), table_name="auctions")
    op.drop_table("auctions")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_account_status"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
