"""Added rejection reason to SellerProfile

Revision ID: e914f9620d06
Revises: f970f76c4f3b
Create Date: 2026-05-18 09:53:46.629792

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e914f9620d06"
down_revision: Union[str, Sequence[str], None] = "f970f76c4f3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seller_profiles", sa.Column("rejection_reason", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller_profiles", "rejection_reason")
    # ### end Alembic commands ###
